/**
 * Anonymization Utility
 *
 * RESPONSIBILITY: Generate and verify pseudonymous donor identifiers for anonymous donations.
 * OWNER: Privacy/Security Team
 * DEPENDENCIES: Node.js built-in crypto
 *
 * Uses HMAC-SHA256 keyed with a server-side secret to derive a consistent,
 * one-way pseudonymous ID from a donor's wallet address. The same wallet
 * address always produces the same pseudonymous ID, but the wallet address
 * cannot be recovered from the pseudonymous ID without the secret.
 */

'use strict';

const crypto = require('crypto');

/**
 * Retrieve the HMAC secret used for pseudonymous ID generation.
 * Falls back to a deterministic test value when running under Jest so that
 * tests are reproducible without requiring environment configuration.
 *
 * @returns {string} The HMAC secret string.
 * @throws {Error} If the secret is missing in a non-test environment.
 */
function getHmacSecret() {
  const secret = process.env.ANONYMOUS_DONATION_SECRET;
  if (secret) return secret;

  // Allow tests to run without environment configuration
  if (process.env.NODE_ENV === 'test') {
    return 'test-anonymous-donation-secret-do-not-use-in-production';
  }

  throw new Error(
    'ANONYMOUS_DONATION_SECRET environment variable is required for anonymous donations. ' +
    'Set a strong, random secret (at least 32 bytes) in your environment configuration.'
  );
}

/**
 * Generate a pseudonymous donor ID from a wallet address using HMAC-SHA256.
 *
 * The resulting ID is a 64-character lowercase hex string prefixed with "anon_"
 * to make anonymous donations visually distinguishable in logs and records.
 *
 * Properties:
 * - Deterministic: same wallet address always produces the same pseudonymous ID.
 * - One-way: the wallet address cannot be recovered from the pseudonymous ID alone.
 * - Consistent: the prefix "anon_" makes anonymous records easy to identify.
 *
 * @param {string} walletAddress - The donor's Stellar wallet address (public key).
 * @returns {string} Pseudonymous ID in the format "anon_<64-hex-chars>".
 * @throws {TypeError} If walletAddress is not a non-empty string.
 */
function generatePseudonymousId(walletAddress) {
  if (typeof walletAddress !== 'string' || walletAddress.trim() === '') {
    throw new TypeError('walletAddress must be a non-empty string');
  }

  const secret = getHmacSecret();
  const hmac = crypto.createHmac('sha256', secret);
  hmac.update(walletAddress.trim());
  const digest = hmac.digest('hex');
  return `anon_${digest}`;
}

/**
 * Verify that a given wallet address corresponds to a pseudonymous ID.
 *
 * This allows a donor to prove their anonymous donation without revealing
 * their wallet address to third parties — they share the wallet address
 * privately with the verifier, who calls this function.
 *
 * @param {string} walletAddress   - The donor's Stellar wallet address to verify.
 * @param {string} pseudonymousId  - The pseudonymous ID stored on the donation record.
 * @returns {boolean} True if the wallet address matches the pseudonymous ID.
 * @throws {TypeError} If either argument is not a non-empty string.
 */
function verifyPseudonymousId(walletAddress, pseudonymousId) {
  if (typeof walletAddress !== 'string' || walletAddress.trim() === '') {
    throw new TypeError('walletAddress must be a non-empty string');
  }
  if (typeof pseudonymousId !== 'string' || pseudonymousId.trim() === '') {
    throw new TypeError('pseudonymousId must be a non-empty string');
  }

  const expected = generatePseudonymousId(walletAddress);

  // Use timingSafeEqual to prevent timing-based side-channel attacks
  const expectedBuf = Buffer.from(expected, 'utf8');
  const actualBuf = Buffer.from(pseudonymousId.trim(), 'utf8');

  if (expectedBuf.length !== actualBuf.length) return false;

  return crypto.timingSafeEqual(expectedBuf, actualBuf);
}

/**
 * Determine whether a pseudonymous ID string looks like one generated by
 * this module (i.e. starts with "anon_" and has the correct length).
 *
 * This is a lightweight format check only — it does NOT verify the HMAC.
 *
 * @param {string} value - The string to check.
 * @returns {boolean} True if the value matches the expected format.
 */
function isPseudonymousId(value) {
  return typeof value === 'string' && /^anon_[0-9a-f]{64}$/.test(value);
}

module.exports = {
  generatePseudonymousId,
  verifyPseudonymousId,
  isPseudonymousId,
};
